# Generated by Django 6.0.5 on 2026-05-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
