# Generated by Django 6.0.5 on 2026-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
    ]
