# Generated by Django 6.0.5 on 2026-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_retry_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
    ]
