# Generated by Django 6.0.5 on 2026-05-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_max_retries"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
