# Generated by Django 6.0.5 on 2026-05-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_processing_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "LOW"), ("MEDIUM", "MEDIUM"), ("HIGH", "HIGH")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
